version: '3.8'

services:
  frontend:
    ports:
      - "3000:80"
    build:
      context: ./frontend
    container_name: frontend
    networks:
      - shared_net

  backend:
    build:
      context: ./backend
    container_name: backend
    expose:
      - 8080
    networks:
      - shared_net
    env_file:
      - .env
    depends_on:
      - postgres
  postgres:
    image: postgres:16
    container_name: postgres-db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - shared_net

  rasa_train:
    image: rasa/rasa:3.6.10
    user: "0:0"
    container_name: rasa_train
    volumes:
      - ./rasa:/app
    command: ["train", "--data", "data", "--config", "config.yml", "--domain", "domain.yml", "--out", "models"]
    networks:
      - shared_net

  rasa:
    image: rasa/rasa:3.6.10
    user: "0:0"
    container_name: rasa
    volumes:
      - ./rasa:/app
    command: ["run", "--model", "models", "--enable-api", "--cors", "*", "--debug"]
    ports:
      - "5005:5005"
    networks:
      - shared_net

  action_server:
    build:
      context: ./rasa
    container_name: rasa-actions
    ports:
      - "5055:5055"
    networks:
      - shared_net

networks:
  shared_net:
    external: true

volumes:
  postgres_data: