version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend
    container_name: backend
    expose:
      - 8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:file:/data/h2db/mydb
      - SPRING_H2_CONSOLE_ENABLED=true
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - app-network
    volumes:
      - h2-data:/data/h2db

  rasa:
    image: rasa/rasa:3.6.10
    container_name: rasa
    expose:
      - 5005
    ports:
      - "5005:5005"
    volumes:
      - ./rasa:/app
      - ./rasa/models:/app/my_models
    command: run --model /app/my_models --enable-api --cors "*" --debug
    networks:
      - app-network

  action_server:
    build:
      context: ./rasa
    container_name: rasa-actions
    ports:
      - "5055:5055"
    networks:
      - app-network
  rasa_train:
    image: rasa/rasa:3.6.10
    volumes:
      - ./rasa:/app
    command: train
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend/dist:/etc/nginx/html
      - ./frontend/dist:/etc/nginx/html:ro

    depends_on:
      - frontend
      - backend
      - rasa
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  h2-data: