version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    depends_on:
      - backend
    networks:
      - shared_net
  backend:
    build:
      context: ./backend
    container_name: backend
    expose:
      - 8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:file:/data/h2db/mydb
      - SPRING_H2_CONSOLE_ENABLED=true
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    volumes:
      - h2-data:/data/h2db
    networks:
      - shared_net
  rasa:
    build:
      context: ./rasa
    container_name: rasa
    ports:
      - "5005:5005"
    user: "999:999"
    volumes:
      - ./rasa/models:/app/models
    command: run --model /app/models --enable-api --cors "*" --debug
    networks:
      - shared_net
  action_server:
    image: rasa/rasa-sdk:3.6.0
    container_name: rasa-actions
    volumes:
      - ./rasa/actions:/app/actions
    ports:
      - "5055:5055"
    networks:
      - shared_net


networks:
  shared_net:
    external: true

volumes:
  h2-data: