version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    depends_on:
      - backend
    networks:
      - shared_net
  backend:
    build:
      context: ./backend
    container_name: backend
    expose:
      - 8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:file:/data/h2db/mydb
      - SPRING_H2_CONSOLE_ENABLED=true
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    volumes:
      - h2-data:/data/h2db
    networks:
      - shared_net
  rasa:
    image: rasa/rasa:3.6.10
    container_name: rasa
    expose:
      - 5005
    ports:
      - "5005:5005"
    volumes:
      - ./rasa:/app
      - ./rasa/models:/app/my_models
    command: run --model /app/my_models --enable-api --cors "*" --debug
    networks:
      - shared_net
  action_server:
    build:
      context: ./rasa
    container_name: rasa-actions
    ports:
      - "5055:5055"
    networks:
      - shared_net
  rasa_train:
    image: rasa/rasa:3.6.10
    user: "999:999"
    volumes:
      - ./rasa:/app
    command: [ "sh", "-c", "id && ls -ld /app/.config && ls -la /app/.config && rasa train" ]
    networks:
      - shared_net

networks:
  shared_net:
    external: true

volumes:
  h2-data: