version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    networks:
      - shared_net

  backend:
    build:
      context: ./backend
    container_name: backend
    expose:
      - 8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:file:/data/h2db/mydb
      - SPRING_H2_CONSOLE_ENABLED=true
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    volumes:
      - h2-data:/data/h2db
    networks:
      - shared_net

  rasa_train:
    image: rasa/rasa:3.6.10
    user: "0:0"
    volumes:
      - ./rasa:/project
    working_dir: /project
    command: ["rasa", "train", "--data", "data", "--config", "config.yml", "--domain", "domain.yml", "--out", "models"]
    networks:
      - shared_net

  rasa:
    image: rasa/rasa:3.6.10
    user: "0:0"
    volumes:
      - ./rasa:/project
    working_dir: /project
    command: ["rasa", "run", "--model", "models", "--enable-api", "--cors", "*", "--debug"]
    ports:
      - "5005:5005"
    networks:
      - shared_net

#  action_server:
#    image: rasa/rasa-sdk:3.6.0
#    user: "0:0"
#    volumes:
#      - ./rasa:/project
#    working_dir: /project
#    command: ["python", "-m", "rasa_sdk", "--actions", "actions"]
#    ports:
#      - "5055:5055"
#    networks:
#      - shared_net

networks:
  shared_net:
    external: true

volumes:
  h2-data: